# Referencing and Cited References

## Autoreferencing

The beauty of the system is that the referencing is all automatised. 

* So to reference an equation use `\@ref(eq:HnApoly)` to obtain equation \@ref(eq:HnApoly)
* So to reference a figure use`\@ref(fig:molarfracPO4)` to obtain figure \@ref(fig:molarfracPO4)
* So to reference an table use`\@ref(tab:ElecAllocTab)` to obtain table \@ref(tab:ElecAllocTab)


## Cited references

I have created and maintained for over 15 years a database written in Microsoft Access of around 2000 articles, most of them photocopied and typed in the database by hand during and after my Ph.D. (yes, I should have a medal!...) but I have to admit that this system is past its time...  I have now switched to Paperpile.  There are many other referencing software out there now  ([a list and comparison can be found here](https://en.wikipedia.org/wiki/Comparison_of_reference_management_software)).  The beauty of them is that they will all export in recognized formats and this is what we care about here. So no more copy/paste of references from some pdf.  We are going into *reproducible research*. This means that all the articles you want to work with will be entered in the reference database of your choice. Make sure you start one ASAP!

In the YAML header, you can now see `bibliography: [book.bib, packages.bib]`. This means that there are files named `book.bib` and `packages.bib` that are located in the same directory as the all the .Rmd files, which when we 'knit', [Pandoc](https://pandoc.org/MANUAL.html) will look for. You can access these `.bib` file in the GitHub directory. There is actually a possibility to add within the `.Rmd` document itself, the text needed for Pandoc to read the references, but unless you only have very few references, this can become very messy quickly. See the [RStudio Bibliographies documentation](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#bibliographies) for more details.

In short, in this file, there is a list of articles which information is coded according to the format chosen. By the way, a lot of the details for the bibliography are available on the [RStudio Bibliographies documentation](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#bibliographies). R Markdown will recognize up to 10 different formats.  The one Paperpile exports is `.bibtex`, so this is the one I have usually add in the YAML header. The filename extension will determine the *rendering* process, so make sure you have the right extension as well.

So, in the `.bib` file I have, the first article appears as

```
@ARTICLE{Kuhne2009-tn,
  title   = "Improving the Traditional Information Management in Natural
  Sciences",
  author  = "K{\"u}hne, Martin and Liehr, Andreas W",
  journal = "Data Sci. J.",
  volume  =  8,
  pages   = "18--26",
  year    =  2009,
  issn    = "1683-1470, 0308-9541",
  doi     = "10.2481/dsj.8.18"
}
```

here is another reference [@Maxwell2018-ht] or this website [@Wikipedia_contributors2018-ia]

The first item after "ARTICLE{" is the unique identifier for the article. The identifier of this article is `Kuhne2009-tn`. When one wants to cite this article, one will say something like "reproducible research has been suggested to become the norm [@Kuhne2009-tn]". And you would code like 

```
"reproducible research has been suggested to become the norm [@Kuhne2009-tn]"
```

If you want to say that "Kühne et al. [-@Kuhne2009-tn] have shown that etc.", you would add a "dash" just before the "@" and code it as such:

```
Kühne et al. [-@Kuhne2009-tn] have shown that etc."
```
If you want to cite several references, you would add a semicolon between the two such as in:

```
"reproducible research has been suggested to become the norm [@Kuhne2009-tn; @Buckheit1995-ls]"
```

Notice that among all the fields from the example above, there are `doi` and `issn`. `doi` stands for "Digital Object Identifier". `issn` stands for International Standard Serial Number (ISSN), which is an eight-digit serial number used to uniquely identify a serial publication. The `doi` value in this example is `10.2481/dsj.8.18`, which is unique in the world.  These `doi` are applied to articles but not only. They are also applied to data. Eventually, all data that will be used in an article will have to have its own `doi` and all the codes that are used to analyze the data will refer to this unique `doi`. This is not quite implemented yet (in 2017), but will likely be by 2022. `doi` or `url` (not added here; stands for Uniform Resource Locator. Quite a mouthful, really, for what it is: a web address) are not necessarily exported from your reference software by default.  Make sure you add this possibility, as `doi` is almost routinely added in the reference list in most journals. 

<br/>

The reference list of the citations will appear right after you place

```
# References
```
at the bottom of your Rmd docucment, if it a single Rmd document, or as a separate chapter for a book.  When rendering your document, the list will appear automatically afterwards, and if you have in text notes, these will appear underneath.

<br/>

### Link to citations
In a single Rmd document (not a book) One very nice feature is to create hyperlinks from the in-text citations to the citations in the reference section. For this, just add `link-citations: true` in the YAML header.

<br/>

### CSL and styling of citations
CSL stands for Citation Style Language. The CSL line command is an option for the citation styles to be used in your document. You can comment it out by adding a "#" in front of it and the default .CSL file will apply without you noticing it. Each journal has its own way of handling how an article/reference should be cited in the text, and in the reference section, and there are hundreds of different styles out there... You can read lots of details on this [CSL primer](http://docs.citationstyles.org/en/stable/primer.html) about how all this works.

While I was writing this tutorial, I did not specify at first the citation style.  And I kept getting, using the same example as before, "(Kühne and Liehr 2009)”, although I wanted "(Kühne and Liehr, 2009)”, i.e., with a comma between the authors and the date, because this is the way I always did it and I think it is a lot better this way. Then I started thinking about the journals for which the inline citations are numbers, sometimes in brackets, sometimes without brackets... what a nightmare...!  Actually it is extremely simple: all this is done automatically when you specify the CSL corresponding to the journal style following which you wish to write.

For this, you can pick at [https://github.com/citation-style-language/styles](https://github.com/citation-style-language/styles) the *.CSL file you are looking for (actually there are too many of them and they are not all displayed). The fastest way is to Google "<journal name> CSL", and you will land on the CSL file you are looking for. I recommend that you click on the `raw` icon on GitHub, and copy all the file in a text editor. Warning! You need to make sure that your text editor does not add any weird formatting or add an extension at the end of the file. I had that problem and I could not see the extension on my computer, although I had the option to display so. Save the file in the same directory as your .Rmd.

So, to go back with my struggling to style the inline citation and the "missing comma", it turns out that the default CSL file uses a "[Chicago author-date format](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_styles)" (I am not sure what this means exactly), which in text styling is "(author date)", without the comma...! If you use "journal-of-hydrology.CSL", you will see that all of a sudden after you `knit`, the commas just appeared...! Eureka! If you use "nature.CSL" (because we all want to be ready when we publish in Nature!), you will see that there are no more in-line citations, just numbers in superscript, hyphenated when needed, and the references are all in order, with the journal names in italics, the journal volume in bold, the year in parenthesis at the end, etc.!  Is not that wonderful? Without your doing anything, other than adding the citation properly in the text following the guidelines above.

You can, if you want and have a lot of time to waste, take existing CSL files and modify them to have your own custom citation style. Make sure you take an "independent" CSL file and modify it. Most of them are dependent upon a "source" or independent one, and the code in the CSL file is just saying how the dependent file should slightly alter the independent one. Good instructions on how to do this can be found on the excellent [CSL primer](http://docs.citationstyles.org/en/stable/primer.html).

